version: '3'
services:
  store-client:
    image: storerestapi/store-client:latest
    container_name: store-client
    environment:
      - APP_PORT=8000
      - STORE_CLIENT_API_BASE_URL=https://api.storerestapi.com
      - STORE_CLIENT_BASE_URL=https://api.storerestapi.com
      - STORE_CLIENT_V1_BASE_URL=https://api.storerestapi.com/v1
      - STORE_CLIENT_PORT=4000
      - STORE_GA=${STORE_CLIENT_PORT}
      - STORE_ADSENSE_CLIENT_ID=${STORE_ADSENSE_CLIENT_ID}
    ports:
      - "4000:4000"
    restart: always
    networks:
      - store-network
networks:
  store-network:
    driver: bridge