version: '3'
services:
  webserver:
    image: storerestapi/store-client:latest
    container_name: store-webserver
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    restart: always
    depends_on:
      - database
      - node-app
    volumes:
      - web-root:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - store-network
volumes:
  mongo-db:
  certbot-etc:
  certbot-var:
  web-root:
networks:
  store-network:
    driver: bridge