version: '3'
services:
  store-client:
    image: storerestapi/store-client:latest
    container_name: store-client
    environment:
      - STORE_CLIENT_API_BASE_URL=${STORE_CLIENT_API_BASE_URL}
      - STORE_GA=${STORE_GA}
      - STORE_ADSENSE_CLIENT_ID=${STORE_ADSENSE_CLIENT_ID}
      - STORE_CLIENT_PORT=${STORE_CLIENT_PORT}
    ports:
      - "4000:${STORE_CLIENT_PORT}"
    restart: always
    networks:
      - store-network
networks:
  store-network:
    external: true