version: '3'
services:
  store-client:
    image: storerestapi/store-client:latest
    container_name: store-client
    environment:
      - STORE_CLIENT_API_BASE_URL=https://api.storerestapi.com
      - STORE_GA='G-FZ9HXX4GYB'
      - STORE_ADSENSE_CLIENT_ID=ca-pub-6922458926245751
      - STORE_CLIENT_PORT=8000
    ports:
      - "4000:8000"
    restart: always
    networks:
      - store-network
networks:
  store-network:
    external: true