version: '3'
services:
  store-client:
    build: .
    container_name: store-client
    environment:
      - STORE_CLIENT_API_BASE_URL=https://api.storerestapi.com
      - STORE_GA=""
      - STORE_ADSENSE_CLIENT_ID=""
      - STORE_CLIENT_PORT=4400
    ports:
      - "4000:4400"
    restart: always
    networks:
      - store-network
networks:
  store-network:
    external: true