# For more information see: https://docs.docker.com/build/ci/github-actions/multi-platform/

name: ci

on:
  push:
    # branches: [ "github-pipeline" ]
    tags:
      - "v*.*"
  # pull_request:
  #   branches: [ "github-pipeline" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/store-client

jobs:
  Frontend-Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Packages
      run: npm install

    - name: Build Angular SSR
      run: npm run build:ssr
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Bundle
        path: |
          dist
          Dockerfile2
          run.sh

  Container-Build-And-Push:
    runs-on: ubuntu-latest
    needs: Frontend-Build
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set UP QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set UP Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login To Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Display Structure of Downloaded Files
        run: ls -R

      - name: Echo 
        run: |
          echo ${{ github.sha }}
          echo ${{ github.workspace }}
          echo ${{ github.ref }}

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: Bundle
      
      - name: Docker Build And Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile2
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          # tags: |
            # ${{ secrets.DOCKER_USERNAME }}/store-client:dummy
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push To Latest Tag
        if: (github.event_name == 'push' && contains(github.ref, '/tags/v'))
        run: |
          docker buildx imagetools create \
            --tag ${{ env.IMAGE_NAME }}:stable \
            ${{ steps.meta.outputs.tags }}
      
      - name: Inspect
        run: |
          docker buildx imagetools inspect ${{ steps.meta.outputs.tags }} --format '{{json .}}'
